categorie/urls.py
from . import views
from django.urls import path

app_name = 'categorie'

urlpatterns = [
   path('categorie/', views.Categorie, name ='categorie'),
   path('ajouter_categorie/',views.ajouter_categorie,name='ajouter_categorie'),
   path('modifier_categorie/<str:pk>',views.modifier_categorie,name='modifier_categorie'),
   path('supprimer_categorie/<str:pk>',views.supprimer_categorie,name='supprimer_categorie'),


]

compte/urls.py
from django.urls import path

from . import views

app_name = 'compte'

urlpatterns = [
   path('', views.inscription, name='inscription'),
   path('acces', views.acces, name='acces'),

]

gestion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('materiel/', include('materiel.urls', namespace='materiel')),
    path('categorie/', include('categorie.urls', namespace='categorie')),
    path('sous_categorie/', include('sous_categorie.urls', namespace='sous_categorie')),
    path('', include('compte.urls', namespace='compte')),
]

sous_categorie/urls.py
from . import views
from django.urls import path

app_name = 'sous_categorie'

urlpatterns = [
   path('sous_categorie/', views.sous_cat, name ='sous_categorie'),
   path('ajouter_souscategorie/', views.ajouter_souscategorie, name='ajouter_souscategorie'),
   path('modifier_souscategorie/<str:pk>',views.modifier_souscategorie,name='modifier_souscategorie'),
   path('supprimer_souscategorie/<str:pk>',views.supprimer_souscategorie,name='supprimer_souscategorie'),
   path('afficher_souscategorie/',views.afficher_souscat,name='afficher_souscategorie'),
   path('ajouter_sous/',views.ajouter_sous,name='ajouter_sous'),
]

sous_categorie/models.py
from urllib import request
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from categorie.models import categorie


class sous_categorie(models.Model):
    Categorie= models.ForeignKey(categorie, null=True, on_delete=models.SET_NULL)
    Nom = models.TextField(max_length=30, null=True)

    def __str__(self):
        return self.Nom

sous_categorie/forms.py
from django.forms import ModelForm
from .models import sous_categorie



class sous_categorieform(ModelForm):
    class Meta:
        model=sous_categorie
        fields='__all__'

sous_categorie/views.py
from django.shortcuts import render,redirect
from .models import sous_categorie
from categorie.models import categorie
from materiel.models import materiel
from .forms import sous_categorieform

def sous_cat(request):
    Categorie = categorie.objects.all()
    Sous_cat = sous_categorie.objects.all()
    Materiel = materiel.objects.all()
    materiel.objects.filter(pk=request.GET.get('Sous_catetorie.id'))
    cat_found = "rien"
    for c in Categorie:
        if c.id == int(request.GET.get('id')):
            cat_found = c
            break
    liste_souscat = []
    for s in Sous_cat:
        if s.Categorie == cat_found:
            liste_souscat.append(s)
    context = {'liste_souscat': liste_souscat, 'cat_found': cat_found, 'categorie': Categorie,'Materiel':Materiel,'Sous_cat':Sous_cat}
    return render(request, 'sous_categorie/sous_categorie.html',context)



def ajouter_souscategorie(request):
   form=sous_categorieform()
   if request.method=='POST':
       form=sous_categorieform(request.POST)
       if form.is_valid():
         form.save()
         return redirect('../../categorie/categorie')
   context={'form':form}
   return render(request,'sous_categorie/ajouter_souscat.html',context)


def ajouter_sous(request):
   form=sous_categorieform()
   if request.method=='POST':
       form=sous_categorieform(request.POST)
       if form.is_valid():
         form.save()
         return redirect('../../categorie/categorie')
   context={'form':form}
   return render(request,'sous_categorie/ajouter_souscat.html',context)


def modifier_souscategorie(request,pk):
    Sous_categorie=sous_categorie.objects.get(id=pk)
    form = sous_categorieform(instance=Sous_categorie)
    if request.method == 'POST':
        form = sous_categorieform(request.POST,instance=Sous_categorie)
        if form.is_valid():
            form.save()
            return redirect('../../categorie/categorie')
    context = {'form': form}
    return render(request,'sous_categorie/ajouter_souscat.html',context)


def supprimer_souscategorie(request,pk):
    Sous_categorie=sous_categorie.objects.get(id=pk)
    if request.method=='POST':
        Sous_categorie.delete()
        return redirect('../../categorie/categorie')
    context={'item':Sous_categorie}
    return render(request,'sous_categorie/supprimer_souscat.html',context)

def afficher_souscat(request):
    Souscat = sous_categorie.objects.all()
    context = {'Souscat':Souscat}
    return render(request, 'sous_categorie/afficher_souscat.html', context)

templates/sous_categorie/afficher_souscat.html
{% extends 'main.html' %}
{% load static %}
{% block content %}


{% for s in Souscat %}
{{ s.Nom }}
{% endfor %}




{% endblock content%}

templates/sous_categorie/ajouter_souscat.html
{% extends 'main.html' %}
{% load static %}
{% block content %}


<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="Enregistrer">
</form>

{% endblock content%}

templates/sous_categorie/sous_categorie.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
&nbsp;&nbsp;&nbsp;

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <a class="btn btn-outline-success me-md-2" type="button" href="{% url 'sous_categorie:ajouter_sous' %}" >Ajouter type materiel</a>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;
<!--
<div class="dropdown">
  <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Type de matériel
  </button>
  <ul class="dropdown-menu">
      {% for s in liste_souscat %}
    <li><a class="dropdown-item" type="button" href="../../materiel/materiel?id={{ s.id }}"> {{ s.Nom }}</a></li>
    {% endfor %}
  </ul>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<div class="dropdown">
  <button class="btn btn-outline-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Modifier type matériel
  </button>
  <ul class="dropdown-menu">
      {% for s in liste_souscat %}
    <li><a class="dropdown-item" type="button" href="{% url 'sous_categorie:modifier_souscategorie'  s.id %}">  {{ s.Nom }}</a></li>
    {% endfor %}
  </ul>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<div class="dropdown">
  <button class="btn btn-outline-danger dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Supprimer type matériel
  </button>
  <ul class="dropdown-menu">
      {% for s in liste_souscat %}
    <li><a class="dropdown-item" type="button" href="{% url 'sous_categorie:supprimer_souscategorie'  s.id %}">  {{ s.Nom }}</a></li>
      {% endfor %}
  </ul>
</div>
-->
<center>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


<div class="btn-group">
  <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Type matériel
  </button>
  <ul class="dropdown-menu">
    {% for s in liste_souscat %}
    <li><a class="dropdown-item" type="button" href="../../materiel/materiel?id={{ s.id }}"> {{ s.Nom }}</a></li>
    {% endfor %}
  </ul>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
  <div class="btn-group">
  <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Modifier type matériel
  </button>
  <ul class="dropdown-menu">
     {% for s in liste_souscat %}
    <li><a class="dropdown-item" type="button" href="{% url 'sous_categorie:modifier_souscategorie'  s.id %}">  {{ s.Nom }}</a></li>
    {% endfor %}
  </ul>
</div>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <div class="btn-group">
  <button type="button" class="btn btn-outline-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Supprimer type matériel
  </button>
  <ul class="dropdown-menu">
   {% for s in liste_souscat %}
    <li><a class="dropdown-item" type="button" href="{% url 'sous_categorie:supprimer_souscategorie'  s.id %}">  {{ s.Nom }}</a></li>
      {% endfor %}
  </ul>
</div>
</center>
{% endblock content%}

templates/sous_categorie/supprimer_souscat.html
{% load static %}

<style>
	body{
    background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
}
#logo{
		}

		body{
			background-color: #ebeff5;
		}


nav{
  display:flex;
  height:80px;
  width:100%;
  background: white;
  align-items: center;
  justify-content:space-between;
  padding:0 50px 0 100px;
  flex-wrap: wrap;
}


nav ul{
  display:flex;
  flex-wrap: wrap;
  list-style-type: none;
}
nav ul li{
  margin:0 5px;
}
nav ul li a{
  color:#f2f2f2;
  text-decoration: none;
  font-size: 18px;
  font-weight: 500;
  padding:8px 15px;
  border-radius: 5px;
  letter-spacing:1px;
  border-bottom:1.5px solid transparent;
  transition:all 0.3s ease;
  position: relative;
}




/* Googlefont Poppins CDN Link */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
}
/* === Google Font Import - Poppins === */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}


		body,
		html {
		 background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
			margin: 0;
			padding: 0;
			height: 100%;
			background-color: #ebeff5;

		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background-color: #ebeff5;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: ;
		}
		.login_btn {
			width: 100%;
			background:  !important;
			color: white !
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}


	</style>
{% block content %}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<center>
<p>Voulez-vous supprimer ce type de matériel?</p>
<form action="{% url 'sous_categorie:supprimer_souscategorie' item.id %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
        <td><a class="btn btn-warning" href="{% url 'categorie:categorie' %}">Annuler</a></td>
            <td><input class="btn btn-danger" type="submit" name="Confirmer" value="Confirmer"></td>
        </tr>
</table>
</form>
    </center>
{% endblock content%}