categorie/urls.py
from . import views
from django.urls import path

app_name = 'categorie'

urlpatterns = [
   path('categorie/', views.Categorie, name ='categorie'),
   path('ajouter_categorie/',views.ajouter_categorie,name='ajouter_categorie'),
   path('modifier_categorie/<str:pk>',views.modifier_categorie,name='modifier_categorie'),
   path('supprimer_categorie/<str:pk>',views.supprimer_categorie,name='supprimer_categorie'),


]

compte/urls.py
from django.urls import path

from . import views

app_name = 'compte'

urlpatterns = [
   path('', views.inscription, name='inscription'),
   path('acces', views.acces, name='acces'),

]

gestion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('materiel/', include('materiel.urls', namespace='materiel')),
    path('categorie/', include('categorie.urls', namespace='categorie')),
    path('sous_categorie/', include('sous_categorie.urls', namespace='sous_categorie')),
    path('', include('compte.urls', namespace='compte')),
]

materiel/urls.py
from . import views
from django.urls import path

app_name = 'materiel'

urlpatterns = [
   path('materiel', views.Materiel, name = 'materiel'),
   path('ajouter_materiel', views.ajouter_materiel, name = 'ajouter_materiel'),
   path('modifier_materiel/<str:pk>',views.modifier_materiel,name='modifier_materiel'),
   path('supprimer_materiel/<str:pk>',views.supprimer_materiel,name='supprimer_materiel'),
   path('afficher_materiel/',views.afficher_mat,name='afficher_materiel'),
]

materiel/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from sous_categorie.models import sous_categorie

class materiel(models.Model):
    STATUS= (
        ('Aucun','Aucun'),
         ('Très bon','Très bon'),
         ('Bon','Bon'),
         ('Moyen','Moyen'),
        ('Mauvais','Mauvais'),
        ('En panne','En panne')
    )
    Type= models.ForeignKey(sous_categorie, null=True, on_delete=models.SET_NULL)
    Numero_inventaire=models.TextField(max_length=30, null=True)
    Numero_serie = models.TextField(max_length=30, null=True)
    Marque = models.TextField(max_length=30, null=True)
    Model = models.TextField(max_length=30, null=True)
    Etat = models.TextField(max_length=30,choices=STATUS)
    #Images = models.ImageField(upload_to="static/images", blank=True, null=True)
    Date_acquisition = models.DateTimeField(null=True)

    def __str__(self):
        return self.Marque

materiel/forms.py
from django.forms import ModelForm
from .models import materiel



class materielform(ModelForm):
    class Meta:
        model=materiel
        fields='__all__'

materiel/views.py
from django.shortcuts import render,redirect
from sous_categorie.models import sous_categorie
from .forms import materielform
from .models import materiel
# Create your views here.
def Materiel(request):
   Sous_cat = sous_categorie.objects.all()
   Materiel = materiel.objects.all()
   souscat_found = "rien"
   for s in Sous_cat:
      if s.id == int(request.GET.get('id')):
         souscat_found = s
         break
   liste_mat = []
   for m in Materiel:
      if m.Type == souscat_found:
         liste_mat.append(m)
   context = {'liste_mat': liste_mat, 'souscat_found': souscat_found, 'Sous_cat': Sous_cat, 'Materiel': Materiel}
   return render(request, 'materiel/materiel.html', context)




def ajouter_materiel(request):
   form=materielform()
   if request.method=='POST':
       form=materielform(request.POST)
       if form.is_valid():
         form.save()
         return redirect('../../categorie/categorie')
   context={'form':form}
   return render(request,'materiel/ajouter_mat.html',context)


def modifier_materiel(request, pk):
   Materiel = materiel.objects.get(id=pk)
   form = materielform(instance=Materiel)
   if request.method == 'POST':
      form = materielform(request.POST, instance=Materiel)
      if form.is_valid():
         form.save()
         return redirect('../../categorie/categorie')
   context = {'form': form}
   return render(request, 'materiel/ajouter_mat.html', context)


def supprimer_materiel(request, pk):
   Materiel = materiel.objects.get(id=pk)
   if request.method == 'POST':
      Materiel.delete()
      return redirect('../../categorie/categorie')
   context = {'item': Materiel}
   return render(request, 'materiel/supprimer_mat.html', context)


def afficher_mat(request):
   Mat = materiel.objects.all()
   context = {'Mat': Mat}
   return render(request, 'materiel/afficher_mat.html', context)

templates/materiel/afficher_mat.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<div class="col-md">
		<div class="card card-body">
<table class="table table-success table-striped">
  <thead>
    <th>Type matériel</th>
                        <th>Numéro inventaire</th>
                        <th>Numéro serie</th>
                        <th>Marque</th>
                        <th>Model</th>
                        <th>Etat</th>
                        <th>Datee d'acquisition</th>
  <th>Mettre à jour</th>
  <th>Supprimer</th><th>Détails</th>
  </thead>
  <tbody>
{% for m in Mat %}
<td> {{ m.Type }}</td>
           <td>{{ m.Numero_inventaire }}</td>
           <td>{{ m.Numero_serie }}</td>
           <td>{{ m.Marque }}</td>
           <td>{{ m.Model }}</td>
           <td>{{ m.Etat}}</td>
           <td>{{ m.Date_acquisition }}</td>
     <td><a type="button" class="btn btn-primary" href="{% url 'materiel:modifier_materiel' m.id %}">Mettre à jour</a></td>
     <td><a type="button" class="btn btn-danger" href="{% url 'materiel:supprimer_materiel'  m.id %}">Supprimer</a></td>
     <td><button type="button" class="btn btn-success" href="">Détails</button></td>
     </tbody>
    {% endfor %}

</table>

        </div>
</div>



{% endblock content %}

templates/materiel/ajouter_mat.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<form action="" method="post" xmlns="http://www.w3.org/1999/html">

    {% csrf_token %}
    {{form}}
    la forme de la date : (aaaa-aa-aa)
    <input type="submit" name="Enregistrer">
</form>
{% endblock content%}

templates/materiel/materiel.html
{% extends 'main.html' %}
{% load static %}
{% block content %}


<hr>
&nbsp;&nbsp;
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <a class="btn btn-success me-md-2" type="button" href="../materiel/ajouter_materiel" >Ajouter un materiel</a>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<div class="col-md">
		<div class="card card-body">
                <table class="table table-success table-striped">
  <thead>
    <th>Type matériel</th>
                        <th>Numéro inventaire</th>
                        <th>Numéro serie</th>
                        <th>Marque</th>
                         <th>Model</th>
                        <th>Etat</th>
                        <th>Datee d'acquisition</th>
  <th>Mettre à jour</th>
  <th>Supprimer</th><th>Détails</th>
  </thead>
  <tbody>
     {% for m in liste_mat %}
          <td> {{ m.Type }}</td>
           <td>{{ m.Numero_inventaire }}</td>
           <td>{{ m.Numero_serie }}</td>
           <td>{{ m.Marque }}</td>
           <td>{{ m.Model }}</td>
           <td>{{ m.Etat}}</td>
           <td>{{ m.Date_acquisition }}</td>
     <td><a type="button" class="btn btn-primary" href="{% url 'materiel:modifier_materiel' m.id %}">Mettre à jour</a></td>
     <td><a type="button" class="btn btn-danger" href="{% url 'materiel:supprimer_materiel'  m.id %}">Supprimer</a></td>
     <td><button type="button" class="btn btn-success" href="">Détails</button></td>
     </tbody>

        {% endfor %}

</table>
       </div>
</div>
{% endblock content%}

templates/materiel/supprimer_mat.html
{% load static %}
<style>
	body{
    background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
}
#logo{
		}

		body{
			background-color: #ebeff5;
		}


nav{
  display:flex;
  height:80px;
  width:100%;
  background: white;
  align-items: center;
  justify-content:space-between;
  padding:0 50px 0 100px;
  flex-wrap: wrap;
}


nav ul{
  display:flex;
  flex-wrap: wrap;
  list-style-type: none;
}
nav ul li{
  margin:0 5px;
}
nav ul li a{
  color:#f2f2f2;
  text-decoration: none;
  font-size: 18px;
  font-weight: 500;
  padding:8px 15px;
  border-radius: 5px;
  letter-spacing:1px;
  border-bottom:1.5px solid transparent;
  transition:all 0.3s ease;
  position: relative;
}




/* Googlefont Poppins CDN Link */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
}
/* === Google Font Import - Poppins === */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}


		body,
		html {
		 background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
			margin: 0;
			padding: 0;
			height: 100%;
			background-color: #ebeff5;

		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background-color: #ebeff5;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: ;
		}
		.login_btn {
			width: 100%;
			background:  !important;
			color: white !
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}


	</style>
{% block content %}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<center>
<p>Voulez-vous supprimer ce matériel?</p>
<form action="{% url 'materiel:supprimer_materiel' item.id %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
        <td><a class="btn btn-warning" href="{% url 'categorie:categorie' %}">Annuler</a></td>
            <td><input class="btn btn-danger" type="submit" name="Confirmer" value="Confirmer"></td>
        </tr>
</table>
</form>
    </center>
{% endblock %}