compte/urls.py
from django.urls import path

from . import views

app_name = 'compte'

urlpatterns = [
   path('', views.inscription, name='inscription'),
   path('acces', views.acces, name='acces'),

]

gestion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('materiel/', include('materiel.urls', namespace='materiel')),
    path('categorie/', include('categorie.urls', namespace='categorie')),
    path('sous_categorie/', include('sous_categorie.urls', namespace='sous_categorie')),
    path('', include('compte.urls', namespace='compte')),
]

compte/models.py
from django.db import models

# Create your models here.

compte/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class creeruser(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

compte/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import creeruser
from django.contrib import messages
# Create your views here.



def inscription(request):
    form=creeruser()
    if request.method=='POST':
        form=creeruser(request.POST)
        if form.is_valid():
            form.save()
            user=form.cleaned_data.get('username')
            messages.success(request,'Compte crée avec succes')
            return redirect('/acces')
    context={'form':form}
    return render(request,'compte/inscription.html',context)

def acces(request):
    context={}
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('categorie/categorie')
        else:
            messages.info(request,"Nom d'utilisateur ou mot de passe incorrect")
    return render(request,'compte/acces.html',context)

templates/compte/acces.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gestion inventaire</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
	body{
    background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
}
#logo{
		}

		body{
			background-color: #ebeff5;
		}


nav{
  display:flex;
  height:80px;
  width:100%;
  background: white;
  align-items: center;
  justify-content:space-between;
  padding:0 50px 0 100px;
  flex-wrap: wrap;
}


nav ul{
  display:flex;
  flex-wrap: wrap;
  list-style-type: none;
}
nav ul li{
  margin:0 5px;
}
nav ul li a{
  color:#f2f2f2;
  text-decoration: none;
  font-size: 18px;
  font-weight: 500;
  padding:8px 15px;
  border-radius: 5px;
  letter-spacing:1px;
  border-bottom:1.5px solid transparent;
  transition:all 0.3s ease;
  position: relative;
}




/* Googlefont Poppins CDN Link */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
}
/* === Google Font Import - Poppins === */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}


		body,
		html {
		 background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
			margin: 0;
			padding: 0;
			height: 100%;
			background-color: #ebeff5;

		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background-color: #ebeff5;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: ;
		}
		.login_btn {
			width: 100%;
			background:  !important;
			color: white !
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}


	</style>

</head>
<body>

<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Connectez-vous</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Nom d'utilisateur..">
						</div>

							<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name="password" placeholder="Mot de passe..">
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Se connecter">
				   		</div>
					</form>
					{% for message in messages %}
                    <p id="messages">{{message}}</p>
                    {% endfor %}
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Voulez-vous créer un compte? <a href="{% url 'compte:inscription' %}" class="ml-2">Créez un compte</a>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

templates/compte/inscription.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gestion inventaire</title>
    <title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<style>
	body{
    background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
}
#logo{
		}

		body{
			background-color: #ebeff5;
		}


nav{
  display:flex;
  height:80px;
  width:100%;
  background: white;
  align-items: center;
  justify-content:space-between;
  padding:0 50px 0 100px;
  flex-wrap: wrap;
}


nav ul{
  display:flex;
  flex-wrap: wrap;
  list-style-type: none;
}
nav ul li{
  margin:0 5px;
}
nav ul li a{
  color:#f2f2f2;
  text-decoration: none;
  font-size: 18px;
  font-weight: 500;
  padding:8px 15px;
  border-radius: 5px;
  letter-spacing:1px;
  border-bottom:1.5px solid transparent;
  transition:all 0.3s ease;
  position: relative;
}




/* Googlefont Poppins CDN Link */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
}
/* === Google Font Import - Poppins === */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}


		body,
		html {
		 background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
			margin: 0;
			padding: 0;
			height: 100%;
			background-color: #ebeff5;

		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background-color: #ebeff5;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: ;
		}
		.login_btn {
			width: 100%;
			background:  !important;
			color: white !
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}


	</style>


</head>
<body>
<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Inscrivez-vous</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>
                        {{form.errors}}
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Inscription">
				   		</div>
					</form>
				</div>
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Avez-vous déja un compte? <a href="{% url 'compte:acces' %}" class="ml-2">Connexion</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nom utilisateur..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Mot de passe...';
		form_fields[4].placeholder='Re-tapez mot de passe...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
<!--
<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Inscription</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>
                        {{form.errors}}
				   		<div class="">
				 			<input class="btn-outline-secondary login_btn" type="submit" value="Inscription">
				   		</div>
					</form>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Avez-vous déja un compte? <a href="{% url 'compte:acces' %}" class="ml-2">Connexion</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
        //Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Nom d'utilisateur..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Mot de passe...';
		form_fields[4].placeholder='Confirmer mot de passe...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>-->
<!--
<form method="post" action="">
    {% csrf_token %}
    {{form.username}}
    {{form.email}}
    {{form.password1}}
    {{form.password2}}
    {{form.errors}}
    <input  type="submit" name="Inscription" value="Inscription">
</form>
<a href="{% url 'compte:acces' %}">Connexion</a>-->
</body>
</html>