categorie/urls.py
from . import views
from django.urls import path

app_name = 'categorie'

urlpatterns = [
   path('categorie/', views.Categorie, name ='categorie'),
   path('ajouter_categorie/',views.ajouter_categorie,name='ajouter_categorie'),
   path('modifier_categorie/<str:pk>',views.modifier_categorie,name='modifier_categorie'),
   path('supprimer_categorie/<str:pk>',views.supprimer_categorie,name='supprimer_categorie'),


]

compte/urls.py
from django.urls import path

from . import views

app_name = 'compte'

urlpatterns = [
   path('', views.inscription, name='inscription'),
   path('acces', views.acces, name='acces'),

]

gestion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('materiel/', include('materiel.urls', namespace='materiel')),
    path('categorie/', include('categorie.urls', namespace='categorie')),
    path('sous_categorie/', include('sous_categorie.urls', namespace='sous_categorie')),
    path('', include('compte.urls', namespace='compte')),
]

materiel/urls.py
from . import views
from django.urls import path

app_name = 'materiel'

urlpatterns = [
   path('materiel', views.Materiel, name = 'materiel'),
   path('ajouter_materiel', views.ajouter_materiel, name = 'ajouter_materiel'),
   path('modifier_materiel/<str:pk>',views.modifier_materiel,name='modifier_materiel'),
   path('supprimer_materiel/<str:pk>',views.supprimer_materiel,name='supprimer_materiel'),
   path('afficher_materiel/',views.afficher_mat,name='afficher_materiel'),
]

sous_categorie/urls.py
from . import views
from django.urls import path

app_name = 'sous_categorie'

urlpatterns = [
   path('sous_categorie/', views.sous_cat, name ='sous_categorie'),
   path('ajouter_souscategorie/', views.ajouter_souscategorie, name='ajouter_souscategorie'),
   path('modifier_souscategorie/<str:pk>',views.modifier_souscategorie,name='modifier_souscategorie'),
   path('supprimer_souscategorie/<str:pk>',views.supprimer_souscategorie,name='supprimer_souscategorie'),
   path('afficher_souscategorie/',views.afficher_souscat,name='afficher_souscategorie'),
   path('ajouter_sous/',views.ajouter_sous,name='ajouter_sous'),
]

categorie/models.py
from urllib import request
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
class categorie(models.Model):
    Categorie = models.TextField(max_length=30, null=True)

    def __str__(self):
        return self.Categorie

categorie/forms.py
from django.forms import ModelForm
from .models import categorie



class categorieform(ModelForm):
    class Meta:
        model=categorie
        fields='__all__'

categorie/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import categorie
from sous_categorie.models import sous_categorie
from .forms import categorieform
from materiel.filters import materielfiltre
from materiel.models import materiel
# Create your views here.
def Categorie(request):
   Materiel = materiel.objects.all()
   Categorie=categorie.objects.all()
   Sous_cat= sous_categorie.objects.all()
   sous_categorie.objects.filter(pk=request.GET.get('Categorie.id'))
   myFilter=materielfiltre(request.GET,queryset=Materiel)
   Materiel=myFilter.qs
   context={'Categorie':Categorie , 'Sous_cat': Sous_cat,'myFilter':myFilter,'Materiel':Materiel}
   return render(request, 'categorie/categorie.html', context)




def ajouter_categorie(request):
   form=categorieform()
   if request.method=='POST':
       form=categorieform(request.POST)
       if form.is_valid():
         form.save()
         return redirect('../../categorie/categorie')
   context={'form':form}
   return render(request,'categorie/ajouter_cat.html',context)



def modifier_categorie(request,pk):
    Categorie=categorie.objects.get(id=pk)
    form = categorieform(instance=Categorie)
    if request.method == 'POST':
        form = categorieform(request.POST,instance=Categorie)
        if form.is_valid():
            form.save()
            return redirect('../../categorie/categorie')
    context = {'form': form}
    return render(request,'categorie/ajouter_cat.html',context)


def supprimer_categorie(request,pk):
    Categorie=categorie.objects.get(id=pk)
    if request.method=='POST':
        Categorie.delete()
        return redirect('../../categorie/categorie')
    context={'item':Categorie}
    return render(request,'categorie/supprimer_categorie.html',context)

templates/categorie/ajouter_cat.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<div class="row">
<div class="col-md-6">
    <div class="card card-body">
<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="Enregistrer">
</form>
    </div>
</div>
</div>





{% endblock content%}

templates/categorie/categorie.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
 <!--
<style>
  body{
    background-image: url("{% static 'images/img_3.png' %}");
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: 100% 100%
  }
</style>-->

<div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <a class="btn btn-outline-success me-md-2" type="button" href="{% url 'materiel:afficher_materiel' %}" >Tout le materiel</a>

</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<div>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
<!--
<div class="dropdown">
  <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Catégorie
  </button>
  <ul class="dropdown-menu">
      {% for c in Categorie %}
    <li><a class="dropdown-item" type="button" href="../../sous_categorie/sous_categorie?id={{ c.id }}"> {{c.Categorie}}</a></li>
    {% endfor %}
  </ul>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<div class="dropdown">
  <button class="btn btn-outline-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Modifier catégorie
  </button>
  <ul class="dropdown-menu">
      {% for c in Categorie %}
    <li><a class="dropdown-item" type="button" href="{% url 'categorie:modifier_categorie'  c.id %}"> {{c.Categorie}}</a></li>
    {% endfor %}
  </ul>
</div>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<div class="dropdown">
  <button class="btn btn-outline-danger dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Supprimer catégorie
  </button>
  <ul class="dropdown-menu">
      {% for c in Categorie %}
    <li><a class="dropdown-item" type="button" href="{% url 'categorie:supprimer_categorie'  c.id %}"> {{c.Categorie}}</a></li>
      {% endfor %}
  </ul>
</div>

    {% for s in Souscat %}
    <li><a class="dropdown-item" type="button" href="{% url 'sous_categorie:modifier_souscategorie' s.id %}">  {{ s.Nom }}</a></li>
    {% endfor %}
-->
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<!-- Example single danger button -->
<center>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <!--
  <div class="btn-group">
  <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Ajouter
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" type="button" href="../ajouter_categorie"> Ajouter catégorie</a></li>
        <li><a class="dropdown-item" type="button" href="{% url 'sous_categorie:ajouter_sous' %}"> Ajouter type de matériel</a></li>
    <li><a class="dropdown-item" type="button" href="{% url 'materiel:ajouter_materiel' %}"> Ajouter matériel</a></li>
  </ul>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>-->
<div class="btn-group">
  <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    catégorie
  </button>
  <ul class="dropdown-menu">
    {% for c in Categorie %}
    <li><a class="dropdown-item" href="../../sous_categorie/sous_categorie?id={{ c.id }}">{{c.Categorie}}</a></li>
     {% endfor %}
  </ul>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>
    <div class="btn-group">
  <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Ajouter
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" type="button" href="../ajouter_categorie"> Ajouter catégorie</a></li>
        <li><a class="dropdown-item" type="button" href="{% url 'sous_categorie:ajouter_sous' %}"> Ajouter type de matériel</a></li>
    <li><a class="dropdown-item" type="button" href="{% url 'materiel:ajouter_materiel' %}"> Ajouter matériel</a></li>
  </ul>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</div>

  <div class="btn-group">
  <button type="button" class="btn btn-outline-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Modifier catégorie
  </button>
  <ul class="dropdown-menu">
     {% for c in Categorie %}
    <li><a class="dropdown-item" href="{% url 'categorie:modifier_categorie'  c.id %}">{{c.Categorie}}</a></li>
    {% endfor %}
  </ul>
</div>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <div class="btn-group">
  <button type="button" class="btn btn-outline-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
    Supprimer catégorie
  </button>
  <ul class="dropdown-menu">
    {% for c in Categorie %}
    <li><a class="dropdown-item" href="{% url 'categorie:supprimer_categorie'  c.id %}">{{c.Categorie}}</a></li>
    {% endfor %}
  </ul>
</div>
</center>
</div>
 <!-- <a href="{% url 'sous_categorie:afficher_souscategorie'%}"> afficher type mat</a>-->
{% endblock content %}

templates/categorie/supprimer_categorie.html
{% load static %}
<style>
	body{
    background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
}
#logo{
		}

		body{
			background-color: #ebeff5;
		}


nav{
  display:flex;
  height:80px;
  width:100%;
  background: white;
  align-items: center;
  justify-content:space-between;
  padding:0 50px 0 100px;
  flex-wrap: wrap;
}


nav ul{
  display:flex;
  flex-wrap: wrap;
  list-style-type: none;
}
nav ul li{
  margin:0 5px;
}
nav ul li a{
  color:#f2f2f2;
  text-decoration: none;
  font-size: 18px;
  font-weight: 500;
  padding:8px 15px;
  border-radius: 5px;
  letter-spacing:1px;
  border-bottom:1.5px solid transparent;
  transition:all 0.3s ease;
  position: relative;
}




/* Googlefont Poppins CDN Link */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}
body{
  min-height: 100vh;
}
/* === Google Font Import - Poppins === */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
}


		body,
		html {
		 background-color: blanchedalmond;
    background-repeat: no-repeat;
    background-position: center;
    background-size: cover;
    min-height: 100vh;
    position: relative;
			margin: 0;
			padding: 0;
			height: 100%;
			background-color: #ebeff5;

		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background-color: #ebeff5;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: ;
		}
		.login_btn {
			width: 100%;
			background:  !important;
			color: white !
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}


	</style>
{% block content %}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<center>
<p>Voulez-vous supprimer cette catégorie?</p>
<form action="{% url 'categorie:supprimer_categorie' item.id %}" method="post">
    {% csrf_token %}
    <table>
        <tr>
        <td><a class="btn btn-warning" href="{% url 'categorie:categorie' %}">Annuler</a></td>
            <td><input class="btn btn-danger" type="submit" name="Confirmer" value="Confirmer"></td>
        </tr>
</table>
</form>
    </center>
{% endblock content%}